export const LifestyleType = {
    Kosher: "Kosher",
    Vegan: "Vegan",
    Vegetarian: "Vegetarian",
    Thiamin: "Thiamin",
    Niacin: "Niacin",
    Riboflavin: "Riboflavin",
    FolicAcid: "Folic Acid",
    Folate: "Folate",
    VitaminC: "Vitamin C",
    VitaminE: " Vitamin E",
    VitaminA: "Vitamin A",
    VitaminB6: "Vitamin B6",
    VitaminB12: "Vitamin B12",
    VitaminD: "Vitamin D",
    Mineral: "Mineral",
    Iron: "Iron",
    Calcium: "Calcium",
    PotassiumChloride: "Potassium Chloride",
    Organic: "Organic",  
    LowSalt: "LowSalt",
    LowSugar: "LowSugar",
};