namespace XperCore.Services
{
    using System.Collections.Generic;
    using XperCore.Model;

    public class AllergensData
    {
        public static List<Allergen> Allergens
        {
            get
            {
                return new List<Allergen>()
                {
                    new Allergen()
                    {
                        Name ="Dairy",
                        Variations = new List<string>()
                        {
                            "Milk",
                            "acidophilus milk",
                            "buttermilk",
                            "buttermilk blend",
                            "buttermilk solids",
                            "cultured milk",
                            "condensed milk",
                            "dried milk",
                            "dry milk solids",
                            "evaporated milk",
                            "fat‐free milk",
                            "fully cream milk powder",
                            "goat’s milk",
                            "Lactaid® milk",
                            "lactose free milk",
                            "low fat milk",
                            "malted milk",
                            "milk derivative",
                            "milk powder",
                            "milk protein",
                            "milk solids",
                            "milk solid pastes",
                            "nonfat dry milk",
                            "nonfat milk",
                            "nonfat milk solids",
                            "pasteurized milk",
                            "powdered milk",
                            "sheep’s milk",
                            "skim milk",
                            "skim milk powder",
                            "sour milk",
                            "sour milk solids",
                            "sweet cream buttermilk powder",
                            "sweetened condensed milk",
                            "sweetened condensed skim milk",
                            "whey",
                            "acid whey",
                            "cured whey",
                            "delactosed whey",
                            "demineralized whey",
                            "hydrolyzed whey",
                            "powdered whey",
                            "reduced mineral whey",
                            "sweet dairy whey",
                            "whey",
                            "whey protein",
                            "whey protein concentrate",
                            "whey powder",
                            "whey solids",
                            "Butter",
                            "artificial butter",
                            "artificial butter flavor",
                            "butter",
                            "butter extract",
                            "butter fat",
                            "butter flavored oil",
                            "butter solids",
                            "dairy butter",
                            "natural butter",
                            "natural butter flavor",
                            "whipped butter",
                            "Casein & caseinates",
                            "ammonium caseinate",
                            "calcium caseinate",
                            "hydrolyzed casein",
                            "iron caseinate magnesium caseinate",
                            "potassium caseinate",
                            "sodium caseinate",
                            "zinc caseinate",
                            "caseinates",
                            "Cheese",
                            "cheese flavor",
                            "cheese food",
                            "cottage cheese",
                            "cream cheese",
                            "imitation cheese",
                            "vegetarian cheeses with casein",
                            "Hydrolysates",
                            "casein hydrolysate",
                            "milk protein hydrolysate",
                            "protein hydrolysate",
                            "whey hydrolysate",
                            "whey protein hydrolysate",
                            "Yogurt",
                            "frozen yogurt",
                            "yogurt powder",
                            "Curds",
                            "Dairy product solids",
                            "Galactose",
                            "Ghee",
                            "Half & Half",
                            "Half and Half",
                            "Ice cream",
                            "Ice milk",
                            "sherbet",
                            "Lactalbumin",
                            "lactalbumin phosphate",
                            "Lactate solids",
                            "Lactyc yeast",
                            "Lactitol monohydrate",
                            "Lactoglobulin",
                            "Lactose",
                            "Lactulose",
                            "Milk fat",
                            "anhydrous milk fat",
                            "Nisin preparation",
                            "Nougat",
                            "Pudding",
                            "Quark",
                            "Recaldent",
                            "Rennet",
                            "rennet casein",
                            "Simplesse",
                            "Sour cream",
                            "sour cream solids",
                            "imitation sour cream",
                            "Sour cream",
                            "Cream",
                            "whipped cream",
                            "milk protein",
                            "AMF Clarified butter",
                            "permeate",
                            "WPC Whey protein isolate",
                            "WPILactaglobulinDe lactosePara casein",
                            "Kappa caseinHyfoama",
                            "Immunoglobulin",
                            "Glycomacropeptide Protease peptone"
                        }
                    },
                    new Allergen()
                    {
                        Name = "Egg",
                        Variations = new List<string>()
                        {
                            "Albumin",
                            "Apovitellin",
                            "Cholesterol free egg substitute",
                            "Dried egg solids",
                            "dried egg",
                            "egg white",
                            "egg yolk",
                            "Egg wash",
                            "Eggnog",
                            "Fat substitutes",
                            "Globulin",
                            "Livetin",
                            "Lysozyme",
                            "Mayonnaise",
                            "Meringue",
                            "meringue powder",
                            "Ovalbumin",
                            "Ovoglobulin",
                            "Ovomucin",
                            "Ovomucoid",
                            "Ovotransferrin",
                            "Ovovitelia",
                            "Ovovitellin",
                            "Powdered eggs",
                            "Silici albuminate",
                            "Simplesse",
                            "Surimi",
                            "Trailblazer",
                            "Vitellin",
                            "Whole egg",
                            "Eggbeaters",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Peanuts",
                        Variations = new List<string>()
                        {
                            "Arachic oil",
                            "Arachis",
                            "Arachis hypogaea",
                            "Artificial nuts",
                            "Beer nuts",
                            "Boiled peanuts",
                            "Cold pressed",
                            "peanut oil",
                            "Crushed nuts",
                            "crushed peanuts",
                            "Earth nuts",
                            "Goober peas",
                            "Ground nuts",
                            "ground peanuts",
                            "Hydrolyzed peanut protein",
                            "Mandelonas",
                            "Mixed nuts",
                            "Monkey nuts",
                            "Nu nuts",
                            "flavored nuts",
                            "Nut pieces",
                            "Nutmeat",
                            "Peanut",
                            "peanut butter",
                            "peanut butter chips",
                            "peanut butter morsels",
                            "Peanut flour",
                            "Peanut paste",
                            "Peanut sauce",
                            "Spanish peanuts",
                            "Virginia peanuts",
                            "peanut syrup",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Tree Nuts",
                        Variations = new List<string>()
                        {
                            "Almond",
                            "Beechnut",
                            "Brazil nut",
                            "Bush nut",
                            "Butternut",
                            "Cashew",
                            "Chestnut",
                            "Coconut",
                            "Filbert",
                            "Ginko nut",
                            "Hazelnut",
                            "Hickory nut",
                            "Lichee nut",
                            "Macadamia nut",
                            "Nangai nut",
                            "Pecan",
                            "Pine nut",
                            "Pistachio",
                            "Shea nut",
                            "Walnut",
                            "Anacardiaceae",
                            "Lecythidaceae",
                            "Burseraceae",
                            "Juglandaceae",
                            "Fagaceae",
                            "Arecaceae",
                            "alt. Palmae",
                            "Betulaceae",
                            "Ginkgoaceae",
                            "shea nut",
                            "Proteaceae",
                            "Karike butter",
                            "piñon",
                            "pinyon",
                            "pigndi",
                            "pigñolia",
                            "pignon nuts",
                            "Pineaceae",
                            "Anacardiaceae",
                            "Rosaceae",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Soy",
                        Variations = new List<string>()
                        {
                            "Bean curd",
                            "Edamame",
                            "Hydrolyzed soy protein",
                            "Kinako",
                            "Koya dofu",
                            "Miso",
                            "Natto",
                            "Okara",
                            "Shoyu",
                            "Soy albumin",
                            "Soy concentrate",
                            "Soy fiber",
                            "Soy formula",
                            "Soy grits",
                            "Soy milk",
                            "Soy miso",
                            "Soy nuts",
                            "Soy nut butter",
                            "Soy protein",
                            "soy protein concentrate",
                            "soy protein isolate",
                            "Soy sauce",
                            "Soy sprouts",
                            "Soya",
                            "Soya flour",
                            "Soybeans",
                            "Soybean granules",
                            "Soybean curd",
                            "Soybean flour",
                            "Soy lecithin",
                            "Soybean paste",
                            "Supro",
                            "Tamari",
                            "Tempeh",
                            "Teriyaki sauce",
                            "Textured soy flour",
                            "Textured soy protein",
                            "Textured vegetable protein",
                            "Tofu",
                            "Yaki-dofu",
                            "Yuba",
                            "freeze dried tofu",
                            "soy pulp",
                            "TSF",
                            "TSP",
                            "TVP",
                            "grilled tofu",
                            "beam curd",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Gluten",
                        Variations = new List<string>()
                        {
                            "Wheat",
                            "including spelt",
                            "farro",
                            "graham",
                            "khorasan wheat",
                            "semolina",
                            "durum",
                            "wheatberries",
                            "Rye",
                            "Barley",
                            "Triticale",
                            "Malt",
                            "malted milk",
                            "malt extract",
                            "malt vinegar",
                            "Brewer's yeast",
                            "Wheat starch",
                            "einkorn",
                            "Oats",
                            "Modified Starch (1440)",
                            "Cereals",
                            "Spelt",
                            "Triticum",
                            "Triticum compactum Host",
                            "Triticum aestivum L",
                            "Triticum durum Desf",
                            "Triticum monococcum L. subsp. monococcum",
                            "Triticum turgidum L. subsp. dicoccon (Schrank) Thell",
                            "Triticum polonicum L",
                            "Triticum durum Desf",
                            "Triticum spelta L",
                            "x Triticosecale ssp. Wittm",
                            "spelta",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Sesame Seeds",
                        Variations = new List<string>()
                        {
                            "sesamol",
                            "benne seed",
                            "sim sim",
                            "Sesame",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Fish",
                        Variations = new List<string>()
                        {
                            "Anchovies",
                            "Bass",
                            "Catfish",
                            "Cod",
                            "Flounder",
                            "Grouper",
                            "Haddock",
                            "Hake",
                            "Halibut",
                            "Herring",
                            "Mahi mahi",
                            "Perch",
                            "Pike",
                            "Pollock",
                            "Salmon",
                            "Scrod",
                            "Sole",
                            "Snapper",
                            "Swordfish",
                            "Tilapia",
                            "Trout",
                            "Tuna",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Crustacean",
                        Variations = new List<string>()
                        {
                            "Barnacle",
                            "Crab",
                            "Crawfish",
                            "crawdad",
                            "crayfish",
                            "ecrevisse",
                            "Krill",
                            "Lobster",
                            "langouste",
                            "langoustine",
                            "Moreton bay bugs",
                            "scampi",
                            "tomalley",
                            "Prawns",
                            "Shrimp",
                            "crevette",
                            "scampi",
                            "clam",
                            "conch",
                            "crawfish",
                            "crayfish",
                            "crustacean",
                            "lobster",
                            "mollusk",
                            "mussel",
                            "oyster",
                            "piddock",
                            "scallop",
                            "shrimp",
                            "snail",
                            "whelk",
                            "crawdad",
                            "crayfish",
                            "ecrevisse",
                            "langouste",
                            "langoustine",
                            "Moreton bay bugs",
                            "scampi",
                            "tomalley",
                            "crevette",
                            "scampi",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Molluscs",
                        Variations = new List<string>()
                        {
                            "Abalone",
                            "Clams",
                            "cherrystone",
                            "geoduck",
                            "littleneck",
                            "pismo",
                            "quahog",
                            "Cockle",
                            "Cuttlefish",
                            "Limpet",
                            "lapas",
                            "opihi",
                            "Mussels",
                            "Octopus",
                            "Oysters",
                            "Periwinkle",
                            "Sea cucumber",
                            "Sea urchin",
                            "Scallops",
                            "Snails",
                            "escargot",
                            "calamari",
                            "Squid",
                            "Whelk",
                            "Turban shell",
                            "cherrystone",
                            "geoduck",
                            "littleneck",
                            "pismo",
                            "quahog",
                            "Lapas",
                            "Opihi",
                            "Escargot",
                            "Calamari",
                            "Turban Shell",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Sulphites",
                        Variations = new List<string>()
                        {
                            "Sulphur dioxide",
                            "Sodium sulfite",
                            "Sodium bisulfite",
                            "Sodium metabisulfite",
                            "Potassium metabisulfite",
                            "Calcium sulphite",
                            "Calcium bisulfite",
                            "Potassium bisulfite",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Wheat",
                        Variations = new List<string>()
                        {
                            "flour",
                            "Bread",
                            "wheat flour",
                            "bread crumbs",
                            "Bulgur",
                            "Cereal extract",
                            "Couscous",
                            "Cracker meal",
                            "Einkorn",
                            "Emmer",
                            "farro",
                            "Farina",
                            "Flour",
                            "atta",
                            "club",
                            "durum",
                            "einkorn",
                            "emmer",
                            "farina",
                            "graham",
                            "kamut",
                            "maida",
                            "semolina",
                            "spelt",
                            "triticale",
                            "triticum",
                            "bromated",
                            "enriched",
                            "high gluten",
                            "high protein",
                            "instant pastry",
                            "phosphated",
                            "soft wheat",
                            "steel ground",
                            "Gluten",
                            "wheat gluten",
                            "vital gluten",
                            "vital wheat gluten",
                            "Kamut",
                            "khorasan wheat",
                            "Malt",
                            "malt extract",
                            "Matzo",
                            "Matzo meal",
                            "matzoh",
                            "matzah",
                            "matza",
                            "Seitan",
                            "Semolina",
                            "Spelt",
                            "Tabbouleh",
                            "Triticale",
                            "Triticum",
                            "Wheat",
                            "whole wheat",
                            "wheat berries",
                            "wheat bran",
                            "whole wheat bread",
                            "whole wheat flour",
                            "whole wheat flour",
                            "wheat germ",
                            "wheat germ oil",
                            "wheat protein isolate",
                            "wheat starch",
                            "wheat sprouts",
                            "sprouted wheat",
                            "Wheatgrass",
                            "einkorn",
                            "Oats",
                            "Modified Starch",
                            "khorasan wheat",
                            "matzoh",
                            "matzah",
                            "matz",
                            "HVP",
                            "Soy sauce",
                            "shoyu",
                            "tamari",
                            "teriyaki sauce",
                            "Club wheat",
                            "Common wheat",
                            "Durum wheat",
                            "Einkorn",
                            "Emmer",
                            "Kamut",
                            "Semolina",
                            "Spelt",
                            "Triticale",
                            "Triticum compactum Host",
                            "Triticum aestivum L",
                            "Triticum durum Desf",
                            "Triticum monococcum L. subsp. monococcum",
                            "Triticum turgidum L. subsp. dicoccon (Schrank) Thell",
                            "Triticum polonicum L",
                            "Triticum durum Desf",
                            "Triticum spelta L",
                            "x Triticosecale ssp. Wittm"
                        }
                    },
                    new Allergen()
                    {
                        Name = "Celery",
                        Variations = new List<string>()
                        {
                            "Aches des Marais",
                            "Ajamoda",
                            "Ajmoda",
                            "Ajwan",
                            "Apii Frutus",
                            "Apio",
                            "Apium graveolens",
                            "Céleri",
                            "Celery Fruit",
                            "Celery Seed",
                            "Fruit de Celeri",
                            "Graine de Céleri",
                            "Karmauli",
                            "Persil des Marais",
                            "Qin Cai",
                            "Smallage",
                            "Selleriefruchte",
                            "Selleriesamen",
                            "Celeriac"
                        }
                    },
                    new Allergen()
                    {
                        Name = "Lupin",
                        Variations = new List<string>()
                        {
                            "Lupinus",
                            "lupine",
                            "Lupinus mutabilis",
                            "Lupinus albus",
                            "Lupinus angustifolius",
                            "lupini",
                            "bluebonnets",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Palm Oil",
                        Variations = new List<string>()
                        {
                            "Elaeis guineensis",
                            "Etyl palmitate",
                            "Glyceryl",
                            "Hydrogenated palm glycerides",
                            "Hyrated Palm Glycerides",
                            "Octyl palmitate",
                            "Palm fruit oil",
                            "Palm kernel",
                            "Palm kernel oil",
                            "PKO",
                            "PHPKO",
                            "Palm stearine",
                            "FP(K)O",
                            "Palmate",
                            "OPKO",
                            "Palmitate",
                            "Palmitic acid",
                            "Palmitoyl oxostearamide",
                            "Palmitoyl tetrapeptide-3",
                            "Palmityl alcohol",
                            "Palmolein",
                            "Sodium kernelate",
                            "Sodium laureth sulfate",
                            "Sodium lauryl lactylate",
                            "Sodium lauryl sulphate",
                            "Sodium lauryl sulfate",
                            "Sodium palm kernelate",
                            "Stearate",
                            "Stearic acid",
                            "Sodium dodecyl Sulphate",
                            "SDS",
                            "NaDS",
                        }
                    },
                    new Allergen()
                    {
                        Name = "MSG",
                        Variations = new List<string>()
                        {
                            "monosodium glutamate",
                            "Hydrolyzed Vegetable Protein",
                            "HVP",
                            "glutamic acid",
                            "Autolyzed yeast",
                            "hydrolyzed corn protein",
                            "hydrolyzed soy protein",
                            "Vegetable Protein",
                            "Hydrolyzed Plant Protein",
                            "Plant Protein Extract",
                            "Sodium Caseinate",
                            "Calcium Caseinate",
                            "Yeast Extract",
                            "Textured Protein",
                            "Autolyzed Protein",
                            "Autolyzed Yeast",
                            "Hydrolyzed Oat Flour",
                            "E 620",
                            "E620",
                            "Monosodium Glutamate",
                            "E 621",
                            "E621",
                            "Monopotassium Glutamate",
                            "E 622",
                            "E622",
                            "Calcium Glutamate",
                            "E 623",
                            "E623",
                            "Monoammonium Glutamate",
                            "E 624",
                            "E624",
                            "natrium glutamate",
                            "hydrolyzed",
                            "calcium caseinate",
                            "sodium caseinate",
                            "Yeast",
                            "Gelatin",
                            "Textured protein",
                            "Soy protein concentrate",
                            "Whey protein isolate",
                            "Protease",
                            "Vetsin",
                            "Ajinomoto",
                            "monosodium salt",
                            "monohydrate",
                            "monosodium glutamate",
                            "monosodium glutamate monohydrate",
                            "monosodium L-glutamate monohydrate",
                            "MSG monohydrate",
                            "sodium glutamate monohydrate",
                            "UNII-W81N5U6R6U",
                            "L-Glutamic acid",
                            "natural flavour",
                            "natural flavor",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Onion",
                        Variations = new List<string>()
                        {
                            "Shallot",
                            "Leek",
                            "Shallots",
                            "Leeks",
                            "asparagus",
                            "Allium",
                            "garlic",
                            "chives",
                            "scallions",
                            "mugwort",
                            "amaryllis",
                            "ornamental alliums",
                            "Purple Sensation",
                            "Globemaster allium",
                            "Gladiator allium",
                            "Corkscrew allium",
                            "Wild onions",
                            "Wild chives",
                            "Rock onion",
                            "Easter lily",
                            "Madonna lily",
                            "Tiger lily",
                            "Orange lily",
                            "Daffodils",
                            "Tulips",
                            "Agapanthus",
                            "Iris",
                            "Alstroemeria",
                        }
                    },
                    new Allergen()
                    {
                        Name = "Garlic",
                        Variations = new List<string>()
                    }
                };
            }
        }
    }
}